// Generated by CoffeeScript 1.7.1
var Util_File;

Util_File = (function() {
  function Util_File() {
    this.fso = new ActiveXObject("Scripting.FileSystemObject");
  }

  Util_File.prototype.echo = function(text) {
    WScript.Echo("" + text);
  };

  Util_File.prototype.createFileList = function(inFolderName) {
    var fsoFolder;
    if (this.fso.FolderExists("" + inFolderName)) {
      fsoFolder = this.fso.GetFolder("" + inFolderName);
      return fsoFolder.Files;
    }
  };

  return Util_File;

})();
